pyamm/user/models.py
# -*- coding: utf-8 -*-
"""User model with LDAP"""
#pylint: disable=unused-import
import hashlib
import os
from base64 import encodestring as encode
from base64 import decodestring as decode
from flask import g, current_app

from flask_login import UserMixin
from ldap3 import MODIFY_ADD, MODIFY_REPLACE, MODIFY_DELETE
from ldap3.core.exceptions import LDAPConnectionIsReadOnlyError

from pyamm.extensions import ldap
#from pyamm.utils import get_current_time
from pyamm.constants import USER_ROLE, ADMIN, USER_STATUS, ACTIVE

USER = dict()

class User(UserMixin):
    """User model.
    This model follows the LDAP object plugin system."""

    def __init__(self, dn, username, data):
        """Create a new user attributes:
         - dn: distinguished name
         - username: the username corresponds with its pyamm email
         - data: all others available ldap attributes"""
        self.dn = dn
        self.username = username
        self.data = data

    def __repr__(self):
        return self.dn

    @property
    def email(self):
        """Add readonly attribute"""
        return self.username

    def get_id(self):
        return self.dn

    # Class methods
    @classmethod
    def authenticate(cls, username, password):
        """Try to authenticate against LDAP"""
        result = ldap.authenticate(username, password)
        return result

    @staticmethod
    def user_is_loaded(distinguishedname):
        """Check if user has already loaded into db"""
        if distinguishedname in USER:
            return USER[distinguishedname]
        else:
            return None

    @classmethod
    def update_user(cls, distinguishedname):
        """Update the account password"""
        if cls.user_is_loaded(distinguishedname):
            del USER[distinguishedname]
            #new_user_data = ldap.get_user_info(distinguishedname)
            #if new_user_data:
            #    current_app.logger.info(USER[distinguishedname])
            #    USER[distinguishedname] = new_user_data
            #    current_app.logger.info(USER[distinguishedname])

pyamm/frontend/views.py
# -*- coding: utf-8 -*-
"""Interface for flask_login amministration. Here the user can log in/out"""
#pylint: disable=unused-import
from uuid import uuid4
from flask_babel import gettext as _
from flask import Blueprint, render_template, current_app, request, flash, \
    url_for, redirect, session, abort
from flask_login import login_required, login_user, current_user, logout_user, \
    confirm_login, login_fresh

from pyamm.user import User
from pyamm.extensions import ldap, login_manager
from pyamm.frontend.forms import LoginForm
from module.ldap3login import AuthenticationResponseStatus


frontend = Blueprint('frontend', __name__)  #pylint: disable=invalid-name


@frontend.route('/', methods=['GET', 'POST'])
def home():
    """Interface for homepage and user login."""
    if current_user.is_authenticated:
        flash(_("You're already logged in as {}").format(current_user.username),
              "success")
        return redirect(url_for('accounts.main'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))
    if form.validate_on_submit():
        result = User.authenticate(form.login.data, form.password.data)
        if result.status == AuthenticationResponseStatus.success: #pylint: disable=no-member
            user = ldap._save_user(result.user_dn,  #pylint: disable=protected-access
                                   result.user_id,
                                   result.user_info,
                                   result.user_groups)
            if login_user(user):
                return redirect(form.next.data or url_for('accounts.main'))
            else:
                flash(_('Sorry, invalid login'), 'danger')
        else:
            flash(_('Sorry, invalid login'), 'danger')
    return render_template('frontend/login.html', form=form)


#@frontend.route('/reauth', methods=['GET', 'POST'])
#@login_required
#def reauth():
#    form = ReauthForm(next=request.args.get('next'))
#
#    if request.method == 'POST':
#        user, authenticated = User.authenticate(current_user.name,
#                                    form.password.data)
#        if user and authenticated:
#            confirm_login()
#            flash('Reauthenticated.', 'success')
#            return redirect('/change_password')
#
#        flash('Password is wrong.', 'danger')
#    return render_template('frontend/reauth.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    """Interface for user logout."""
    logout_user()
    session.pop('ldapPW', None)
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.home'))


#@frontend.route('/signup', methods=['GET', 'POST'])
#def signup():
#    if current_user.is_authenticated:
#        return redirect(url_for('user.profile'))
#    return redirect(url_for('index'))
#
#    form = SignupForm(next=request.args.get('next'))
#
#    if form.validate_on_submit():
#        user = User()
#        form.populate_obj(user)
#
#        db.session.add(user)
#        db.session.commit()
#
#        if login_user(user):
#            flash('Signed up', 'success')
#            return redirect(form.next.data or url_for('user.profile'))
#
#    return render_template('frontend/signup.html', form=form)


##@frontend.route('/change_password', methods=['GET', 'POST'])
#def change_password():
#    user = None
#    if current_user.is_authenticated:
#        if not login_fresh():
#            return login_manager.needs_refresh()
#        user = current_user
#    elif 'activation_key' in request.values and 'email' in request.values:
#        activation_key = request.values['activation_key']
#        email = request.values['email']
#        user = User.query.filter_by(activation_key=activation_key) \
#                         .filter_by(email=email).first()
#
#    if user is None:
#        abort(403)
#
#    form = ChangePasswordForm(activation_key=user.activation_key)
#
#    if form.validate_on_submit():
#        user.password = form.password.data
#        user.activation_key = None
#        db.session.add(user)
#        db.session.commit()
#
#        flash("Your password has been changed, please log in again", "success")
#        return redirect(url_for("frontend.login"))
#
#    return render_template("frontend/change_password.html", form=form)
#
#
#@frontend.route('/reset_password', methods=['GET', 'POST'])
#def reset_password():
#    form = RecoverPasswordForm()
#
#    if form.validate_on_submit():
#        user = User.query.filter_by(email=form.email.data).first()
#
#        if user:
#            flash('Please see your email for instructions on '
#                  'how to access your account', 'success')
#
#            user.activation_key = str(uuid4())
#            db.session.add(user)
#            db.session.commit()
#
#            return render_template('frontend/reset_password.html', form=form)
#        else:
#            flash('Sorry, no user found for that email address', 'error')
#
#    return render_template('frontend/reset_password.html', form=form)

pyamm/user/__init__.py
# -*- coding: utf-8 -*-

from models import User, USER
from views import user

pyamm/user/views.py
# -*- coding: utf-8 -*-
"""Views for basic account administration.

Missing: password recover
"""

#pylint: disable=unused-import
from flask import Blueprint, render_template, send_from_directory, request, \
    current_app, flash, session
from pyamm.user.models import User


user = Blueprint('user', __name__, url_prefix='/user') #pylint: disable=invalid-name

pyamm/templates/layouts/base.html
<!DOCTYPE html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}{{ page_title }}{% endblock %} - pyamm</title>
        <meta name="description" content="PyAmm">
        <meta name="author" content="Software Workers Srl">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="/static/favicon.png" rel="icon" type="image/png">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet">
        {% block css %}{% endblock %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/3.0.15/autosize.min.js"></script>
        {% block js %}{% endblock %}
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </head>
    <body>
    <!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

        {% block topbar %}
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('frontend.index') }}">Pyamm</a>
                        <a class="navbar-brand" href="{{ url_for('accounts.main') }}">Panel</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#"
                                    class="dropdown-toggle notification-indicator" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        {{ current_user.email }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('user.profile') }}">Profile</a></li>
                                    <li><a href="{{ url_for('user.password') }}">Password</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for('frontend.logout') }}">Log out</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{{ url_for('frontend.login') }}">Log in</a></li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        {% endblock %}

        {% block container %}
        <div class="container">
            {% block flash_message %}
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        {% for category, msg in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ msg|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            {% endblock %}

            {% block body %}{% endblock %}
        </div>
        {% endblock %}

        <footer>
        </footer>

    </body>
</html>

pyamm/templates/layouts/user.html
{% extends 'layouts/base.html' %}

{% block body %}
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <b>{{ current_user.name }}</b>
            </div>
            <div class="panel-body">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation" class="{% if request.endpoint == 'user.profile' %}active{% endif %}">
                        <a href="{{ url_for('user.profile') }}">{% trans %}Profile{% endtrans%}</a>
                    </li>
                    <li role="presentation" class="{% if request.endpoint == 'user.password' %}active{% endif %}">
                        <a href="{{ url_for('user.password') }}">Password</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        {% block panel_right %}
        {% endblock %}
    </div>
</div>
{% endblock %}